[package]
name = "firesim"
version = "0.1.0"
authors = ["linus"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = "0.3.14"
ggez = "0.5"
cgmath = "0.17.0"
